language: php
php:
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.4
      env: COVERALLS_VERSION=1.*

before_install: composer require "satooshi/php-coveralls:${COVERALLS_VERSION}" --no-update

install: composer update --prefer-source --no-interaction --dev
  
after_script: ./vendor/bin/coveralls -v

script: ./vendor/bin/phpunit

