language: php
php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.4

before_script: 
  - composer install
  - composer update
  
after_script: ./vendor/bin/coveralls -v

script: ./vendor/bin/phpunit

